#!/usr/bin/env fish

tar -czvf private.tar.gz -C ~/ .ssh

tar -czvf thunderbird.tar.gz -C ~/ .thunderbird
tar -czvf mozilla.tar.gz -C ~/ .mozilla

tar -czvf caprine.tar.gz -C ~/ .config/Caprine
tar -czvf riot.tar.gz -C ~/ .config/Riot
tar -czvf discord.tar.gz -C ~/ .config/discord
