#!/usr/bin/env fish
# To be run from /mnt on the source machine.
# Copies sensitive, non-version-controllable configuration files.

tar -czvf ssh.tar.gz -C ~/ .ssh
tar -czvf keyrings.tar.gz -C ~/ .local/share/keyrings

tar -czvf riot.tar.gz -C ~/ .config/Riot
tar -czvf discord.tar.gz -C ~/ .config/discord
