#!/usr/bin/env fish

# create the trash folder for Ranger
mkdir -p ~/.local/share/Trash/files

# colorize pacman
sudo sed -i "s/#Color/Color/g" /etc/pacman.conf

# install rust-nightly and leetcode-cli
rustup install nightly
cargo +nightly install leetcode-cli
