#!/usr/bin/env fish

# create the trash folder for Ranger
mkdir -p ~/.local/share/Trash/files

# clone KAM repository
# TODO: make it so this doesn't ask for password
sudo git clone root@kam.mff.cuni.cz:/aux/admin/GIT/kam.git /etc/kam
sudo printf "[user]\n\temail = tom@kam.mff.cuni.cz\n\tname = Tomáš Sláma" >> /etc/kam/.git/config
